version: "3.8"

services:
  backend:
    build: ./backend
    container_name: my-backend
    env_file:
      - .env
    environment:
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      # optionally set AWS keys here for local testing (not recommended for production)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - webnet
    restart: always

  nginx:
    build: ./nginx
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
